spring:
  application:
    name: produto
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product
    username: postgres
    password: 1234567
    pool:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org:
      springframework:
        r2dbc:
          core: DEBUG
